[[NEW_FEATURES]]
//=== New in Version {VERSION_MAJOR}.{VERSION_MINOR}
=== New in Version 2.7
_WSJT-X 2.7_ introduced a new program called *QMAP*, new Special
Operating Activities *Q65 Pileup* and *SuperFox mode*, an option to
*Update Hamlib* at the click of a button, a new program feature 
*Message System*, and a number of other enhancements and bug fixes.

- *QMAP* and *Q65 Pileup* mode are of particular interest to those engaged
  in Earth-Moon-Earth (EME) communication, but other applications may
  be found for them as well.  QMAP is derived from MAP65, an older program used since 2007 for
  EME. QMAP provides single-polarization receive-only capabilities for
  any one of the 60-second submodes of Q65, and the associated 30-second 
  submode with the same tone spacing.  It allows you to monitor
  all traffic in a 90 kHz sub-band while conducting EME QSOs in the
  usual way with _WSJT-X_.  Q65 Pileup mode helps DX operators using
  Q65 in pileup circumstances with many simultaneous callers and very
  weak signals, such as those experienced by 6-meter EME DXpeditions.
  Further details on QMAP and Q65 Pileup mode are available in a
  Quick-Start guide posted here:
  https://wsjt.sourceforge.io/Quick_Start_WSJT-X_2.7_QMAP.pdf

- *SuperFox mode* behaves operationally like the original
  Fox-and-Hound mode but uses a new constant envelope waveform for
  Fox's transmissions. Messages can be transmitted simultaneously to
  as many as 9 Hounds with no signal-strength penalty, resulting in a
  system gain of about +10 dB compared to the older Fox-and-Hound
  operation with 5 slots.  Further details on SuperFox mode can be
  found in the Quick-Start guide posted here:
  https://wsjt.sourceforge.io/SuperFox_User_Guide.pdf
  
- *Message System* allows structured plain text messages to be sent
  to your QSO partner, requesting a QSY to another frequency or submode,
  for example during contests.  In addition, a number of preset messages 
  can be sent. Features and usage of the Message System are described
  fully in <<Message_System,Section 9>> of this Guide.

- A button *Update Hamlib* now appears on the *File | Settings |
  Radio* tab.  On Windows it allows the user to automatically download
  and install the latest version of the rig-control features in
  Hamlib.  The previously used version is backed up, so you can easily
  revert the procedure if necessary. Names and dates of the active and
  backup versions are clearly displayed.

- Spotting to *PSK Reporter* has been made more efficient.  Redundant
  spots are omitted, and posts are spread more widely in time. If
  your station locator is changed, for example during portable
  operations, your new locator will be sent automatically to PSK
  Reporter.

- *Fox* mode now provides more convenient handling of the two callsign
  queues, and the *Fox Log* window displays statistical data on recent QSO
  rate.

- The cty.dat file can now be updated by clicking a button on the
  *File | Settings | Colors* tab.

- The FT Roundup message protocol now allows the exchange of static
  4-digit numbers in place of serial numbers. This extends the
  usability of the FT RU protocol for other contest types.

- Features for main-window switching between modes have been enhanced
  so that submode and status of the *Sh* and *Fast* checkboxes are
  saved and restored by mode.  Right-click events were made more
  intuitive and consistent.  Right-clicking the Q65 button enables Q65
  Pileup mode, and a left-click brings you back to the normal Q65
  mode.  Right-click on the JT65 button switches to JT9 mode.

- Message averaging is now allowed only when *VHF features* are
  enabled.  Main window text box labels are changed to read "`Single
  Period Decodes`" and "`Average Decodes`" when averaging is enabled.
  
Further details on minor changes can be found in the Release Notes,
accessible from the _WSJT-X_ *Help* menu. 
  
  
=== New in Version 2.8

Version 2.8 of _WSJT-X Improved_ incorporates all developments that were tested in the
2.7.1 devel versions, with the addition of several new items.
The list below summarizes some of the key features of v2.8. For a more detailed description of
_WSJT-X Improved_ additional capabilities  please refer to  <<WSJT-X_IMPROVED,Section 16>>.

- *Wait features* are provided to assist making QSOs more efficienctly by removing the 
 need to constantly call a station who does not reply initially, or under difficult propagation
 conditions such as  bad QSB.  Three different functions are available, *Wait and Reply*, 
 *Wait and Call* and *Wait and Pounce*.

- *Full Duplex Mode (FDM)* When enabled, WSJT-X is able to transmit and receive at the same time.
 Very useful for satellite operation, where the audio source is normally set to
 the transponder downlink, and possibly also in some special situations where you
 want to monitor your own transmit signal (e.g. using a webSDR as audio source).
 FDM works for the slow modes (FT8, FT4, Q65, etc.) as well as for fast modes
 like MSK144.
 Several modifications to AutoSeq were made to prevent QSOs with the own callsign.
 Your own messages are highlighted in the Band Activity window in the color you
 selected for "Transmitted message".

- *TCI support*  TCI – Transceiver Control Interface is a network interface for control, data
 transfer and synchronization between a transceiver/receiver, logger, digital
 software, skimmer, other software and external power amplifier, band filters,
 antenna switch, radio station controller and other devices.
 The TCI interface supports both TCI CAT control and TCI audio. Note that when
 switching from non-TCI to TCI or TCI audio or back, a restart of the program
 is required, or at least recommended.
 A new Refresh button in Settings/Audio that can be used to reload the audio
 device list.
 
- *Additional functions for JT65, JT9, JT4* introducing AutoSeq, so that these modes
 can now be operated (almost) as easily as the 77-bit modes (FT8, FT4, MSK144, Q65, FST4).
 The *Wait* and *Filter* features  now also work for JT65, JT9 and JT4.
 Also CQ: First, CQ: MaxDist, CQ: Max dB and CQ: Min dB are now operational for
 these modes.  This makes the JT9 mode interesting again for DX, because
 it is more than 3 dB more sensitive than FT8, and also very frequency-efficient.
 
- *Freely selectable FT8 frequencies for band hopping* enabling the user to
 define up to 8 FT8 frequencies himself by spinboxes, or simplyenter the QRG via the keypad.
 The default frequencies for the new spinboxes are set to the standard DXp QRGs.
 But now you can enter any frequency, and it is remembered, so you can monitor  
 for example you local QRG, or a DXpedition using other frequencies, or the like.
 
- *Display PWR and SWR, and Halt Tx when SWR > 2.5*: You can now stop the transmission automatically
 if the SWR exceeds 2.5, e.g. if you have accidentally selected the wrong antenna. Also the transmit
 PWR is then displayed in real time. It works with most of the modern rigs as long as they are 
 connected via one of the Hamlib rig drivers or via FLRig.
 
- *Band Buttons* The band select buttons can be switched on/off via the View menu.
 Clicking on a band button causes the program to search the frequency table for
 the band/mode "default" frequency. Users can define these "default" QRGs. Just set the "Pref" 
 checkboxes in Settings/Frequencies according toyour needs. Right-clicking the band buttons 
 will take you directly to the main DXpedition frequencies when in FT8 mode (or to the 
 intercontinental QRG on 6m).With the latest Hamlib version, ATU on/off status is now remembered per band
 for Yaesu FT-991. Very useful together with the new band buttons! Support of this
 function for more rigs may follow in the future. This feature is brand new!
 
- *New technology for the Band Hopping checkboxes* As with the band buttons, the static Band Hopping
 checkboxes for FT8, FT4 and MSK144 now also get their frequencies from the Settings / Frequencies list.
 This has the advantage that you can define yourself which QRGs should be hopped to.
 Useful for contests, or when there are local frequencies (e.g. 160m in Japan).
 
- *New option to automatically remove saved audio files after 30 days* activated in the *Save*
 menu and helps to keep the total size of thesaved data within reasonable limits. If active, 
 such files are removed when the program is started. 
 
- *File Saving Reminder* In both _QMAP_ and _WSJT-X_ the Monitor button changes colour if File saving 
 is active.
 
- *Download CALL3.TXT master files* With one click* means you can now download the latest CALL3.TXT
 file either for terrestrial use or EME. Your previous CALL3.TXT file is backed up.
 The CALL3.TXT file for terrestrial use contains grids for more than ten thousand
 frequently heard callsigns, most of them 6-digit grids.
 
- *More powerful filters* Introduction of Quick Filters accessible via the new "Filters" menu directly
 from the main window. Hide stations from certain continents or DXCC with one click.
 Hide, ignore or highlight stations worked before on band, or worked today or
 yesterday. The latter is particularly useful for contests, or for time zones where
 00:00 UTC is not at midnight but sometime in the middle of the day.
 A new Ignore List allows you to either highlight unwanted stations, ignore them
 with CQ: XYZ, Wait&Pounce and Best S+P, or hide them completely. Click the new
 "Ignore" button to add a station to the list. You can delete the Ignore List
 via the new "Erase Ignore List" entry in the File menu. Bypass your filter settings with one click
 with the BP checkbox.
 
- *Better support of high resolution monitors* DPI scaling results in a better and proportionally
 correct display of the control elements for 2K, 4K, 8K, monitors. 
 
- *Useful additions for EME operation*  A new "kHz without k" checkbox allows setting of kHz
 frequency offsets without 'k'suffix via the band select field. EME operators can now for example directly
 enter something like "250", press the RETURN key, and it will bring them to XXXX.250 MHz instead of 250 MHz.
 A new option has been added  to enable Tx shift relative to an Rx sked frequency to enable wide
 in-band separation of Tx and Rx frequencies.  Buttons are now provided for quick selection of *Echo* mode,
 as well as six sub-modes of Q65.  Submodes 15A, 15B and 15C can now be decoded with EME delay, for experimental
 purposes.
 
- *New technology for the Audible Alerts* Especially on Windows, less resources are required when playing
 the sound files, which are now located in the bin directory of the installation. This
 has the advantage that also on Linux and macOS you won't have to copy the sounds folder to your
 home directory anymore.
 
- *Improvements to the logging of QSOs*  New option to log the ADIF field <SAT_MODE>.
 Log automatically is now also possible when not in contest mode. Use this only
 when really needed (e.g. for remote operation). Two new checkboxes in Settings/Reporting: 
 “Fill missing grids with ‘ZZ00’” and “Log 4-digit grids”. This is for better support of certain
 contests. Note that the restriction to 4-digit grids already applies automatically for certain special
 operating activities. The new checkbox only needs to be used if this should also
 apply to normal modes.
 
 - *Better support of SuperFox mode for Wait and Call* It is now possible to activate Wait & Call in SuperHound
 mode even if the SuperFox has not yet been received. However, “blind calling” is still prevented to
 keep the bands clean!

 - *Improvements for Fox operators* Inadvertent transmissions on frequencies overlapping the WSPR sub-bands is 
 now prevented. Furthermore, the Fox operator is notified if there is probably another Fox station on the frequency.
 
- *Numerous code improvements and fixes*

 
 
 
 
 
 
 






