name: CI

on:
  push:
    branches: [develop]
  pull_request:
    branches: [develop]
  workflow_dispatch:

jobs:
  macos:
    uses: ./.github/workflows/build-macos.yml
    with:
      version: "3.0.0"
      hamlib_branch: "4.7.0"
    secrets: inherit

  linux:
    uses: ./.github/workflows/build-linux.yml
    with:
      version: "3.0.0"
      hamlib_branch: "4.7.0"
    secrets: inherit

  windows:
    uses: ./.github/workflows/build-windows.yml
    with:
      version: "3.0.0"
      hamlib_branch: "4.7.0"
    secrets: inherit
