name: CI

on:
  push:
    branches: [develop]
  pull_request:
    branches: [develop]
  workflow_dispatch:

jobs:
  macos:
    uses: ./.github/workflows/build-macos.yml
    with:
      version: "3.0.0"
      hamlib_branch: "4.7.1"
      arch: "arm64"
      runner: "macos-15"
      deployment_target: "11.0"
    secrets: inherit

  macos-intel:
    uses: ./.github/workflows/build-macos.yml
    with:
      version: "3.0.0"
      hamlib_branch: "4.7.1"
      arch: "x86_64"
      runner: "macos-15-intel"
      deployment_target: "10.13"
    secrets: inherit

  linux:
    uses: ./.github/workflows/build-linux.yml
    with:
      version: "3.0.0"
      hamlib_branch: "4.7.1"
    secrets: inherit

  windows:
    uses: ./.github/workflows/build-windows.yml
    with:
      version: "3.0.0"
      hamlib_branch: "4.7.1"
    secrets: inherit
